name: Flake8-linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=120
    - name: Upload flake8.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: flake8 report
        path: flake8.txt
